# Tutorial 0: Python warm-up

[![View notebooks on Github](https://img.shields.io/static/v1.svg?logo=github&label=Repo&message=View%20On%20Github&color=lightgrey)](https://github.com/phlippe/uvadlc_notebooks/blob/master/docs/tutorial_notebooks/tutorial10/Adversarial_Attacks.ipynb)

**Author:** Alejandro Monroy

This tutorial is not meant to be a self-contained guide to learn Python from scratch, but a brief recap of the tools that you need to know to be able to understand the rest of the tutorials.

## 1. Python basics

### 1.1. Primitive Data Types

Python supports several primitive data types that are the building blocks for data manipulation:

- **Integers (`int`)**: Whole numbers, e.g., `1`, `42`, `-7`.
- **Floating-point numbers (`float`)**: Numbers with decimal points, e.g., `3.14`, `-0.001`.
- **Strings (`str`)**: Sequences of characters, e.g., `"hello"`, `"Python"`.
- **Booleans (`bool`)**: Logical values representing `True` or `False`.

These primitive data types are essential for performing basic operations and storing simple values in Python.

In [11]:
# Integer
x = 10
print("x = ", x)
print("Type of x: ", type(x))

# Float
y = 3.14
print("\ny = ", y)
print("Type of y: ", type(y))

# String
name = "Alice"
print("\nname = ", name)
print("Type of name: ", type(name))

# Boolean
condition_1 = x == 11
print("\ncondition_1 = ", condition_1)
print("Type of condition_1: ", type(condition_1))
condition_2 = x <= 11
print("condition_2 = ", condition_2)
print("Type of condition_2: ", type(condition_2))

x =  10
Type of x:  <class 'int'>

y =  3.14
Type of y:  <class 'float'>

name =  Alice
Type of name:  <class 'str'>

condition_1 =  False
Type of condition_1:  <class 'bool'>
condition_2 =  True
Type of condition_2:  <class 'bool'>


### 1.2. Mathematical Operations

Python supports various mathematical operations for numerical computations:

- **Basic Arithmetic**: `+` (addition), `-` (subtraction), `*` (multiplication), `/` (division).
- **Exponentiation**: `**` (power), e.g., `2 ** 3` results in `8`.
- **Modulus**: `%` (remainder), e.g., `10 % 3` results in `1`.
- **Floor Division**: `//` (integer division), e.g., `10 // 3` results in `3`.

### 1.3. Control Structures

Control structures dictate the flow of execution in a program:

- **Conditional Statements**: `if`, `elif`, `else` for decision making.
- **Loops**: `for` to iterate over sequences, `while` to repeat as long as a condition is true.

In [6]:
# Example code that prints all integers between 1 and 30 that are divisible by 2 and 3
for num in range(1, 30):
    if num % 2 == 0 and num % 3 == 0:
        print(num)

6
12
18
24


### 1.4. Functions
A Python function is a block of reusable code that performs a specific task. It can take inputs (called parameters), execute a series of statements, and return an output. Functions help in organizing code, making it more readable and reusable.

In [12]:
# Example of Python function
def greet(name):
    """
    Greets a person by printing a personalized message including their name.

    Args:
        name (str): The name of the person to greet.

    Returns:
        str: Personalized greeting message.
    """
    return f"Hello, {name}! How are you today?"

# Example usage
greet("Alex")

'Hello, Alex! How are you today?'

### 1.5. Classes
A Python class is a blueprint for creating objects. It defines a set of attributes and methods that the created objects will have. Classes allow for object-oriented programming, which helps in organizing code into reusable and related components.

In [14]:
# Example of Python class
class Person:
    """
    A class used to represent a person with a name and age, and to greet them with a personalized message.
    """

    def __init__(self, name, age):
        """
        Initializes a new instance of the Person class.

        Args:
            name (str): The name of the person.
            age (int): The age of the person.
        """
        self.name = name
        self.age = age

    def birthday(self):
        """
        Increments the age of the person by 1.
        """
        self.age += 1

    def greet(self):
        """
        Greets the person by returning a personalized message including their name and age.

        Returns:
            str: Personalized greeting message.
        """
        return f"Hello, {self.name}! You are {self.age} years old. How are you today?"

# Example usage
alex = Person("Alex", 25)
print(alex.greet())
alex.birthday()
print(alex.greet())

Hello, Alex! You are 25 years old. How are you today?
Hello, Alex! You are 26 years old. How are you today?


<div class="alert alert-block alert-info"> 
<b>Tip:</b> If you are going to use a piece of code more than once, it is usually a good practice to encapsulate it into a function. 
</div>

### 1.6. Collections
- List: mutable ordered sequence of objects
- Tuple: inmutable ordered sequence of objects
- Set: unordered sequence of items
- Dictionary: mutable collection of key-value pairs

| Collection Type | Mutable | Ordered | Duplicate Elements | Syntax Example          |
|-----------------|---------|---------|--------------------|-------------------------|
| List            | ✔️      | ✔️      | ✔️                 | `[1, 2, 3]`             |
| Tuple           | ❌      | ✔️      | ✔️                 | `(1, 2, 3)`             |
| Set             | ✔️      | ❌      | ❌                 | `{1, 2, 3}`             |
| Dictionary      | ✔️      | ❌      | Keys: ❌, Values: ✔️ | `{'a': 1, 'b': 2}` |

We can define collections by comprehension. For example, we can define a list with the first 10 powers of 10 as follows:

In [6]:
# By extension
l1 = [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]

# Using a for loop
l2 = []
for i in range(10):
    l2.append(2**i)

# Using list comprehension
l3 = [2**i for i in range(10)]

print(l1)
print(l2)
print(l3)

# Check if all lists are equal
assert l1 == l2 == l3

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]


We can also define other types of collections by comprehension. For example, let's define a dictionary where the keys are the integers from 0 to 9 and the values the corresponding power of 2:

In [7]:
# By extension
d1 = {0: 1, 1: 2, 2: 4, 3: 8, 4: 16, 5: 32, 6: 64, 7: 128, 8: 256, 9: 512}

# Using a for loop
d2 = {i: 2**i for i in range(10)}
for i in range(10):
    d2[i] = 2**i

# Using dictionary comprehension
d3 = {i: 2**i for i in range(10)}

print(d1)
print(d2)
print(d3)

# Check if all dictionaries are equal
assert d1 == d2 == d3

{0: 1, 1: 2, 2: 4, 3: 8, 4: 16, 5: 32, 6: 64, 7: 128, 8: 256, 9: 512}
{0: 1, 1: 2, 2: 4, 3: 8, 4: 16, 5: 32, 6: 64, 7: 128, 8: 256, 9: 512}
{0: 1, 1: 2, 2: 4, 3: 8, 4: 16, 5: 32, 6: 64, 7: 128, 8: 256, 9: 512}


💡 **Note:** In the previous cells we used an `assert` statement. The `assert` statement is used for debugging purposes. It tests a condition, and if the condition is `False`, it raises an `AssertionError` with an optional error message. This helps in identifying and fixing bugs by ensuring that certain conditions hold true during the execution of the program. In this case, we include it to make sure/show that the three lists are indeed equal!

Hello

## 2. Handling multi-dimensional data with Numpy

NumPy is a powerful library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is widely used in data science, machine learning, and scientific computing due to its performance and ease of use.

In [18]:
import numpy as np

# Example of numpy arrays
# 1D array
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
print(b)


[1 2 3 4 5 6]
[[1. 2. 3.]
 [4. 5. 6.]]


### 2.1. Numpy array attributes

These are some of the most important attributes of numpy arrays:

| Method                        | Description                                                                 |
|-------------------------------|-----------------------------------------------------------------------------|
| `ndarray.shape`               | Returns the shape (dimensions) of the array.                                |
| `ndarray.dtype`               | Returns the data type of the array elements.                                |
| `ndarray.ndim`                | Returns the number of dimensions of the array.                              |
| `ndarray.size`                | Returns the total number of elements in the array.                          |
| `ndarray.T`                   | Returns the transpose of the array.                                         |

In [21]:
print("Array:\n", a)
print("Shape:", a.shape)
print("Number of dimensions: ", a.ndim)
print("Number of elements: ", a.size)
print("Data type: ", a.dtype)

print("\nArray:\n", b)
print("Shape:", b.shape)
print("Number of dimensions: ", b.ndim)
print("Number of elements: ", b.size)
print("Data type:", b.dtype)

Array:
 [1 2 3 4 5 6]
Shape: (6,)
Number of dimensions:  1
Number of elements:  6
Data type:  int64

Array:
 [[1. 2. 3.]
 [4. 5. 6.]]
Shape: (2, 3)
Number of dimensions:  2
Number of elements:  6
Data type: float32


### 2.2. Elemental operations between numpy arrays

In [10]:
### Operations between numpy arrays
u1 = np.array([1, 2, 3])
u2 = np.array([2, 4, 6])
print("Addition of u1 and u2:", u1 + u2)
print("Subtraction of u1 and u2:", u1 - u2)
print("Element-wise multiplication of u1 and u2:", u1 * u2)
print("Element-wise division of u1 and u2:", u1 / u2)

Addition of u1 and u2: [3 6 9]
Subtraction of u1 and u2: [-1 -2 -3]
Element-wise multiplication of u1 and u2: [ 2  8 18]
Element-wise division of u1 and u2: [0.5 0.5 0.5]


Another commonly used vector operation is the dot product. Mathematically, the dot product (denoted with $\cdot$) of two vectors $a = [a_1, a_2, ..., a_N]$, $b = [b_1, b_2, ..., b_N]$ is
$$
a \cdot b = a_1b_1 + a_2b_2 + ... + a_Nb_N.
$$

Notice that:
- The input is two vectors, but the output is a single scalar!
- Both input vectors need to have the same length

In [11]:
print("Dot product of u1 and u2:", np.dot(u1, u2))

Dot product of u1 and u2: 28


🤔 _Task for you:</b> Apply the formula above by hand and check that the result we got is indeed correct!_

### Higher-dimensional arrays
We can also have higher-dimensional arrays, which can be used to represent matrices. The element-wise operations that we just saw also apply in this case. Now, we also perform matrix multiplication using the `@` operator or `np.matmul`:

In [12]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[2, 4], [6, 8]])
print("Addition of m1 and m2:\n", m1 + m2)
print("Multiplication of m1 and m2:\n", np.matmul(m1, m2))
print("Multiplication of m1 and m2:\n", m1 @ m2)

Addition of m1 and m2:
 [[ 3  6]
 [ 9 12]]
Multiplication of m1 and m2:
 [[14 20]
 [30 44]]
Multiplication of m1 and m2:
 [[14 20]
 [30 44]]


In [13]:
type(m1)

numpy.ndarray

### 2.3. Important metohds of numpy arrays

### Array Manipulation

| Method                        | Description                                                                 |
|-------------------------------|-----------------------------------------------------------------------------|
| `ndarray.reshape(newshape)`   | Returns a new array with the same data but a new shape.                     |
| `ndarray.flatten()`           | Returns a copy of the array collapsed into one dimension.                   |
| `ndarray.sort(axis=-1)`       | Sorts the array along the specified axis.                                   |
| `ndarray.concatenate((a1, a2, ...), axis=0)` | Joins a sequence of arrays along an existing axis.         |


In [26]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n ", a)
print("Shape: ", a.shape)

# The following methods turns the array into a 1D array with the same elements
a_flattened = a.flatten()
print("\nFlattened array:\n", a_flattened)
print("Shape of flattened array: ", a_flattened.shape)


Array:
  [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)

Flattened array:
 [1 2 3 4 5 6]
Shape of flattened array:  (6,)


### Mathematical Operations
| Method                        | Description                                                                 |
|-------------------------------|-----------------------------------------------------------------------------|
| `ndarray.dot(b)`              | Returns the dot product of two arrays.                                      |
| `ndarray.sum(axis=None)`      | Returns the sum of the array elements over the specified axis.              |
| `ndarray.prod(axis=None)`     | Returns the product of the array elements over the specified axis.          |
| `ndarray.cumsum(axis=None)`   | Returns the cumulative sum of the array elements over the specified axis.   |
| `ndarray.cumprod(axis=None)`  | Returns the cumulative product of the array elements over the specified axis.|

In [31]:
a = np.array([[2, 2, 2, 2], [3, 3, 3, 3]])
print("Array:\n ", a)

print("Sum of the array across columns: ", a.sum(axis=0))
print("Sum of the array across all dimensions: ", a.sum())
print("Product of the array across rows:; ", a.prod(axis=-1))

Array:
  [[2 2 2 2]
 [3 3 3 3]]
Sum of the array across columns:  [5 5 5 5]
Sum of the array across all dimensions:  20
Product of the array across rows:;  [16 81]


🤔 **Food for thought:** Why did we use `axis = -1` in the last example? What would be an equivalent value for the axis?

### Statistical Methods
| Method                        | Description                                                                 |
|-------------------------------|-----------------------------------------------------------------------------|
| `ndarray.mean(axis=None)`     | Returns the mean of the array elements over the specified axis.             |
| `ndarray.std(axis=None)`      | Returns the standard deviation of the array elements over the specified axis.|
| `ndarray.var(axis=None)`      | Returns the variance of the array elements over the specified axis.         |
| `ndarray.min(axis=None)`      | Returns the minimum value of the array elements over the specified axis.    |
| `ndarray.max(axis=None)`      | Returns the maximum value of the array elements over the specified axis.    |
| `ndarray.argmin(axis=None)`   | Returns the indices of the minimum values along an axis.                   |
| `ndarray.argmax(axis=None)`   | Returns the indices of the maximum values along an axis.                   |

In [46]:
a = np.array([[1, 3, 2, 0, 2], [10, 5, 5, 2, 6]])
print("Array:\n ", a)
print("Minimum value across columns: ", a.min(axis=-1))
print("Mean across all dimensions: ", a.mean())

Array:
  [[ 1  3  2  0  2]
 [10  5  5  2  6]]
Minimum value across columns:  [0 2]
Mean across all dimensions:  3.6


## 3. Handling multi-dimensional data (with more options) with Pandas


In [48]:
import pandas as pd

df = pd.DataFrame(np.random.random(size=(100, 7)))
df.head()

0         1         2         3         4         5         6
0  0.793329  0.337908  0.380384  0.033518  0.198487  0.380001  0.438908
1  0.012718  0.310516  0.427287  0.123414  0.331358  0.915896  0.407620
2  0.915002  0.544574  0.619468  0.102989  0.451320  0.508073  0.167655
3  0.685601  0.402225  0.354264  0.732573  0.243896  0.478226  0.246439
4  0.548756  0.350888  0.780341  0.476442  0.345441  0.266626  0.329939

We can add column names:

In [50]:
df.columns = [f"Column {i}" for i in range(1, 8)]
df.head()

Column 1  Column 2  Column 3  Column 4  Column 5  Column 6  Column 7
0  0.793329  0.337908  0.380384  0.033518  0.198487  0.380001  0.438908
1  0.012718  0.310516  0.427287  0.123414  0.331358  0.915896  0.407620
2  0.915002  0.544574  0.619468  0.102989  0.451320  0.508073  0.167655
3  0.685601  0.402225  0.354264  0.732573  0.243896  0.478226  0.246439
4  0.548756  0.350888  0.780341  0.476442  0.345441  0.266626  0.329939

Let's switch to something more interesting that a randomly generated dataset. We can import datasets from a file and store them in Pandas DataFrames:

pd.load_csv()

Pandas is built on top of NumPy. This means that the values in the dataframe are stored in NumPy arrays, and therefore we can access all the attributes and methods that we saw before! Isn't that awesome?

In [54]:
print(type(df["Column 2"].values))

<class 'numpy.ndarray'>


In [ ]:
print("Mean ")